spring:
  config:
    import:
      - optional:configserver:http://localhost:8888
      - optional:classpath:keys.properties
  application:
    name: merchant-service
  profiles:
    active: ${PROFILE}