spring:
  config:
    import:
      - optional:configserver:http://localhost:8888
      - optional:classpath:keys.properties
  application:
    name: eureka-server
  profiles:
    active: ${PROFILE:dev}